apiVersion: v1
kind: Service
metadata:
  name: maestro-api
spec:
  selector:
    app: maestro-api
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maestro-api
  labels:
    heritage: maestro-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maestro-api
    spec:
      containers:
        - name: maestro-api
          command:
            - "/bin/sh"
            - "-c"
            - "/app/maestro start -v3 -p 80 --incluster"
          image: quay.io/tfgco/maestro:v{{ .Chart.Version }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MAESTRO_EXTENSIONS_PG_HOST
              value: {{ .Values.maestro.postgres_host }}
            - name: MAESTRO_EXTENSIONS_PG_PORT
              value: "{{ .Values.maestro.postgres_port }}"
            - name: MAESTRO_EXTENSIONS_PG_USER
              value: {{ .Values.maestro.postgres_user }}
            - name: MAESTRO_EXTENSIONS_PG_PASS
              value: {{ .Values.maestro.postgres_password }}
            - name: MAESTRO_EXTENSIONS_PG_DATABASE
              value: {{ .Values.maestro.postgres_database }}
            - name: MAESTRO_GOOGLE_CLIENT_ID
              value: {{ .Values.maestro.google_clientid }}
            - name: MAESTRO_GOOGLE_CLIENT_SECRET
              value: {{ .Values.maestro.google_clientsecret }}
            - name: MAESTRO_OAUTH_ACCEPTEDDOMAINS
              value: {{ .Values.maestro.oauth_domains }}
            - name: MAESTRO_EXTENSIONS_REDIS_URL
              value: {{ .Values.maestro.redis_url }}
