---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maestro-worker
  labels:
    heritage: maestro-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maestro-worker
    spec:
      containers:
        - name: maestro-worker
          command:
            - "/bin/sh"
            - "-c"
            - "/app/maestro worker -v3 --incluster"
          image: quay.io/tfgco/maestro:v{{ .Chart.Version }}
          imagePullPolicy: Always
          env:
            - name: MAESTRO_EXTENSIONS_PG_HOST
              value: {{ .Values.maestro.postgres_host }}
            - name: MAESTRO_EXTENSIONS_PG_PORT
              value: "{{ .Values.maestro.postgres_port }}"
            - name: MAESTRO_EXTENSIONS_PG_USER
              value: {{ .Values.maestro.postgres_user }}
            - name: MAESTRO_EXTENSIONS_PG_PASS
              value: {{ .Values.maestro.postgres_password }}
            - name: MAESTRO_EXTENSIONS_PG_DATABASE
              value: {{ .Values.maestro.postgres_database }}
            - name: MAESTRO_EXTENSIONS_REDIS_URL
              value: {{ .Values.maestro.redis_url }}
