language: go
go:
- 1.8
services:
- docker
cache:
  directories:
  - $GOPATH/pkg
sudo: true
install:
  # helm
- wget -q ${HELM_URL}/${HELM_TGZ}
- tar xzfv ${HELM_TGZ}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
  # s3cmd
- wget -O- -q http://s3tools.org/repo/deb-all/stable/s3tools.key | sudo apt-key add -
- sudo wget -O/etc/apt/sources.list.d/s3tools.list http://s3tools.org/repo/deb-all/stable/s3tools.list
- sudo apt-get update && sudo apt-get install s3cmd
  # setup-ci
- make setup-ci
script:
- make test-ci
after_success:
- bash after-success.sh
env:
  global:
  - secure: DgyQ0pT+P+aMj3iCshPiHmG7sDx95QVC3Qq+ITD2769dz1Sep6Bvz99emLM84b5g1V3aT7hvjg+RE/A8yrpCHZfuiNeiNY5XQR58zaKcShoRmYxyuSJPLUxbu12AVrbaQJFbwEs5evc2BDHBAN1+YTaEGIkAeEfAjyw4DpxZZNm8NHB5JHSKuZmcdoPz7ASdysenLzWxon/fxRB5nXVK2Jky/+0uFhMpJPJhvpQBE0SLrZ6L9mSduIehcrnl/qvJnVIWZDkMb1qRgSDZ3rXSFk05T1bZtbeQXQRWcz2AtHfvmhR51ufsfI7tZ/n65U/J40hq8OcSLjJyA4GOy0Xt7Vai0pjOyv5XBvwyCqTcl1ptm3Yf5aW75kiCsMlBGXv8dK8vI7IY4iXLPnipSKVK1UkgCfSQNRsHlf0vJ21k/7KRAZnhmtS39WcVapOed/UoXIWDgMH5PcrnkuZPylLONlHSE5pbevnObHsRGh86YSAxx0RS+RXJ2qlF6l8QYT5S0TDDHtpJ9qlJHpD6jJCMm9/0txTBgMDfaksmFLVnEEKhZrWW/lDk8YCDNz+Sb2Pq1cBRXzi2+i10b21XS4pYBbxyNecanwxNtr8Bia7yQbJHZF1zByUz4IaMA1pX7B2XGA46gDpav6edKWtN9es/HBxH8FgH7EG1dECjGBNXlw8=
  - secure: No6skbtjA8gQKB/Z6cOAgyPMIJ4yt++yCo0JRQxEeKHP4sTK8gdZ2Xpt0Lk6XXQcBfpz2IG06hsfGkMznnKIdcCh2IT1Y4Iwj7U2k5fAgRoWxGWNi9EGms08fRaW6DEHxAEI1dqpw8GSpDZsiHM4ZlM32QYu25/v1lVDOSCwbGmKq85FctIlxpuiUdZwrM4FY9AzI3x5tcYMUGiVsVdl+kEVcphImurLuzxDSBXH1/tb5dRYDv4Qo6bfnj5kIWDNPpEH1sK8jddjQ46BP13Ad9KAhNPcIvx6oerMvHiZ9VKFzYuo0fety9Ax/jxZdppNSvs3PtbM9slR1qKOlOSyYS00nTH5j+xvhygurJ9ffcmbZFqeFLI7rEHcT8BYGGZgK6Hb4nbuqp6julWndfpcjqntxCThKp5/z74aZn1jPshVh+0Zud48ne9kHpAqwReW8MsKVPAObzGIUcZypdQt6TYb4AvJtvea81Z9KB2jleBDOC7YggbMGKE/5PjfQREry39ba6WVCOv0b4tgDjAdlIP2/XPJ34CS69YF5dC8dVAegJ+PzTNEwPwXbGywRxuU9SoXHS+V6YswcEhRvNYgpL3vmzj6tmM3oOOg/fX0vtWddguN8romoGHCJbYnNjEMvP10x6tcZSBxz5DzxWhGfBnnpNxtqmvfm0aKw7azbD0=
  - secure: G8sM4Xqxuj27/MlmKPJq2REfogZh3aDgOWoY3nJ8bd6hQHmdisnRYCyC9t5PDkBJMZKTA0YYO4WossrTAoYrHXUN4iB1Kq/np8xM5N22D85LG3t2asMw9ft8fHAtrC5IHN3UFxFU1w3o/2zKGjpskPHvBKcIKeNG+QgQrxwPjYCyNj7ELfXvqesoocD8C7pkLgZw3jVOo/hpp2L9wVaniKIYKKO4ecYuIomlZUntorx98hD+ZmV7bkW5zQYvvPBhZOGB/KYJb58tkavGE4fFp6sgmhiC96BLRd9SLmye6tLTeT0HOHg7A7Hg8XHWz1U19TL+B0desrt65o06FyunN3DB+eJXQEVYujfP0x/n9LEucf1U6Cb/idgA73ZvHapthkLeG14yXqL/8r/kYqwS8Q9pNMmykZjhY81KmpQyKuOM1uyxD5K/avh2yi/KtvU1WEjWudJOWDw8AoLGUpnFd0c+nQQBMhX3GG9B3jGLqzIjX1Fe1sYELAgQYQgumyosNf1GBG3IaLbmeQ8I+qdZt0+QmLLIZl2KmG2vuQmDDFDIYTnLg/0KEzUsjfNoG+fl4qZfHnNme5ZpkY5FlgNTnIQ8HharrTYFMaj33l3MCn7cNZKLTKIPOtzLsjdbIHmSjiSHd5w/At2iil7tUjpPvisr2oRFDywEXsG98EkXUN0=
  - secure: RqM2jIU8eKMX+nuYZqtGZ14ihYZhlkUL7PknkIlBZGfgvpfSOg7Zv9OCUAimkEhwnMRQPzWF5Hh4lCvdzzGyFx4c1lP9tS1+2Asj5EXo/oFeBQeov1x+usjNTmlOe6wcjqTi54VwxSRhImBcLOLi83H5Cs1jdvp0ThqVvSlPkoQLz6tjT8oQq2UZw4+6L8W+t/firUbXXwhYcOi+irqRSKxZbsD6cn1S11aLGdljEEJDkZQj+Yx37mu/7ttdNOmH3xqP2PppG+Qi8BzgTM1CclJxWu+pcj3EJlGrMRDeZ4zMpN8Tya0/xQrAdlJUuEq34+zsJyEYZYSR12bDcwHbDDkEx0dMH6ARU/SCKRPLtLAN+bWH90ZrZpq2Q/CzhtBX2fYCUUKid/PWuanMYmUSYhmKrbuPN0QfSyjICTiSvL6p96tHqNwbvM2NJ9PhQV3PYllyOWFFskdXVx+m5dIVuTKOfdEoBXQnBGWg+W6I65OLgMDDOkOKx58MBVxE0SdW/PPKN6lChwMas4m3v8Q0dfZquIyaDnZ8S6ID8xlgM2CifykYDed7AvzGOr71jUmQBgKMtY9B70q990UdU9MYuxNdV4Rp/VOTMfjxAqgAGGLKUv9OCar4JqeKARlgQMtdP5Qt9Q6Y7hmBsN/TEt3IuFpggTDPAk8yh49NyGsgUy8=
before_install:
- openssl aes-256-cbc -K $encrypted_cea9c093ef67_key -iv $encrypted_cea9c093ef67_iv
  -in id_rsa_travis.enc -out id_rsa -d
- mv id_rsa ~/.ssh/id_rsa
