version: '3'
services:
  k3s_server:
    image: "rancher/k3s:v1.19.11-k3s1"
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=maestro
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443  # Kubernetes API Server

  k3s_agent:
    image: "rancher/k3s:v1.19.11-k3s1"
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=maestro

  postgres:
    image: postgres:9.6.9
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=maestro
    - POSTGRES_USER=maestro
    - POSTGRES_PASSWORD=maestro

  redis:
    image: redis:5.0.10-alpine
    ports:
    - "6379:6379"

