apiVersion: v1
data:
  {{- if ne .Values.tls_crt "" }}
  tls.crt: {{ .Values.tls_crt }}
  {{- end}}
  {{- if ne .Values.tls_key "" }}
  tls.key: {{ .Values.tls_key }}
  {{- end}}
  {{- if ne .Values.newrelic_app ""}}
  newrelicapp: {{ .Values.newrelic_app }}
  {{- end}}
  {{- if ne .Values.newrelic_key ""}}
  newrelickey: {{ .Values.newrelic_key }}
  {{- end}}
kind: Secret
metadata:
  name: maestro-secret
  namespace: maestro
type: Opaque
