---
name: maestro-boomforce-game
game: game-name
occupiedTimeout: 3600
containers:
- name: game-container-0
  image: maestro-dev-room:latest
  imagePullPolicy: Never
  requests:
    cpu: 250m
    memory: 150Mi
  limits:
    cpu: 400m
    memory: 400Mi
  ports:
  - containerPort: 8080
    protocol: TCP
    name: tcp
  env:
  - name: MAESTRO_HOST_PORT
    value: 192.168.64.1:8080
    valueFrom:
      secretKeyRef:
        name: ""
        key: ""
  - name: POLLING_INTERVAL_IN_SECONDS
    value: "20"
    valueFrom:
      secretKeyRef:
        name: ""
        key: ""
  - name: PING_INTERVAL_IN_SECONDS
    value: "10"
    valueFrom:
      secretKeyRef:
        name: ""
        key: ""
shutdownTimeout: 10
autoscaling:
  min: 1
  max: 0
  up:
    cooldown: 90
    delta: 1
    trigger:
      time: 60
      usage: 70
      threshold: 80
      limit: 90
    metricsTrigger:
    - type: cpu
      delta: 0
      time: 60
      usage: 80
      threshold: 80
      limit: 90
  down:
    cooldown: 120
    delta: 1
    trigger:
      time: 120
      usage: 50
      threshold: 80
      limit: 0
    metricsTrigger:
    - type: cpu
      delta: 0
      time: 120
      usage: 50
      threshold: 80
      limit: 0
