---
name: scheduler-name
game: game-name
occupiedTimeout: 180
shutdownTimeout: 100
autoscaling:
  min: 2
  up:
    cooldown: 30
    delta: 1
    trigger:
      usage: 70
      time: 60
      threshold: 80
  down:
    cooldown: 30
    delta: 1
    trigger:
      usage: 50
      time: 60
      threshold: 80
containers:
- name: nginx
  image: nginx:alpine
  ports:
  - containerPort: 8080
    protocol: TCP
    name: tcp
