---
name: scheduler-with-two-containers
game: game-name
occupiedTimeout: 180
shutdownTimeout: 180
autoscaling:
  min: 2
  up:
    cooldown: 30
    delta: 1
    trigger:
      usage: 70
      time: 60
      threshold: 80
  down:
    cooldown: 30
    delta: 1
    trigger:
      usage: 50
      time: 60
      threshold: 80
containers:
- image: nginx:alpine
  name: nginx
  ports:
  - containerPort: 8081
    protocol: TCP
    name: tcp
- image: redis:alpine
  name: redis
  ports:
  - containerPort: 6379
    protocol: TCP
    name: tcp
