{{- if eq .Values.global.redis_location "on-cluster" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: maestro-redis
  name: maestro-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: maestro-redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maestro-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maestro-redis
    spec:
      containers:
      - name: redis
        image: redis:3.2
        command:
          - redis-server 
        ports:
          - containerPort: 6379
{{- end}}
