extensions:
  pg:
    host: "localhost"
    port: 8765
    user: "maestro"
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: "maestro"
    connectionTimeout: 100
  redis:
    url: redis://localhost:6363
    connectionTimeout: 200
watcher:
  autoScalingPeriod: 10
  lockKey: "maestro-lock-key"
  lockTimeoutMs: 180000
  gracefulShutdownTimeout: 300
worker:
  syncPeriod: 10
  gracefulShutdownTimeout: 300
scaleUpTimeoutSeconds: 60
scaleDownTimeoutSeconds: 60
deleteTimeoutSeconds: 60
pingTimeout: 60
updateTimeoutSeconds: 60
sentry:
  url: ""
newrelic:
  app: "maestro"
  key: ""
oauth:
  acceptedDomains: 
  - "example.com"
  - "other.com"
