extensions:
  pg:
    host: "localhost"
    port: 8765
    user: "maestro"
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: "maestro"
    connectionTimeout: 100
watcher:
  lockKey: "maestro-lock-key"
  lockTimeoutMs: 180000 
