internal_api:
  port: 8081
  gracefulShutdownTimeout: 10s
  metrics:
    enabled: true
  healthcheck:
    enabled: true
management_api:
  port: 8080
  gracefulShutdownTimeout: 10s
adapters:
  schedulerStorage:
    postgres:
      url: "postgres://maestro:maestro@postgres:5432/maestro?sslmode=disable"
  operationFlow:
    redis:
      url: "redis://redis:6379/0"
  operationStorage:
    redis:
      url: "redis://redis:6379/0"
