internalApi:
  port: 8081
  gracefulShutdownTimeout: 10s
  metrics:
    enabled: true
  healthcheck:
    enabled: true
roomsApi:
  port: 8080
  gracefulShutdownTimeout: 10s
adapters:
  portAllocator:
    random:
      range: 60001-60010
  roomStorage:
    redis:
      url: "redis://localhost:6379/0"
  instanceStorage:
    redis:
      url: "redis://localhost:6379/0"
  schedulerStorage:
    postgres:
      url: "postgres://maestro:maestro@localhost:5432/maestro?sslmode=disable"
  schedulerCache:
    redis:
      url: "redis://localhost:6379/0"
  runtime:
    kubernetes:
      masterUrl: "https://127.0.0.1:6443"
      kubeconfig: "./kubeconfig.yaml"
