extensions:
  pg:
    host: "localhost"
    port: 8765
    user: "maestro_test"
    pass: ""
    poolSize: 20
    maxRetries: 3
    database: "maestro_test"
    connectionTimeout: 100
  redis:
    url: redis://localhost:6363
    connectionTimeout: 200
newrelic:
  app: maestro
  key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
