internal_api:
  port: 8082
  gracefulShutdownTimeout: 10s
  metrics:
    enabled: true
  healthcheck:
    enabled: true
adapters:
  schedulerStorage:
    postgres:
      url: "postgres://maestro:maestro@postgres:5432/maestro?sslmode=disable"
  operationFlow:
    redis:
      url: "redis://redis:6379/0"
  operationStorage:
    redis:
      url: "redis://redis:6379/0"
  runtime:
    kubernetes:
      masterUrl: "https://k3s_server:6443"
      kubeconfig: "./kubeconfig.yaml"
  portAllocator:
    random:
      range: 60001-60010
  roomStorage:
    redis:
      url: "redis://redis:6379/0"
  instanceStorage:
    redis:
      url: "redis://redis:6379/0"
workers:
  syncInterval: 10s
  stopTimeoutDuration: 1m
services:
  roomManager:
    roomInitializationTimeoutMillis: 120000