internal_api:
  port: 8082
  gracefulShutdownTimeout: 10s
  metrics:
    enabled: true
  healthcheck:
    enabled: true
adapters:
  schedulerStorage:
    postgres:
      url: "postgres://maestro:maestro@localhost:5432/maestro?sslmode=disable"
  operationFlow:
    redis:
      url: "redis://localhost:6379/0"
  operationStorage:
    redis:
      url: "redis://localhost:6379/0"
  runtime:
    kubernetes:
      masterUrl: "https://127.0.0.1:6443"
      kubeconfig: "./kubeconfig.yaml"
workers:
  syncInterval: 10s
  stopTimeoutDuration: 1m
services:
  roomManager:
    roomInitializationTimeoutMilis: 10000