dependencies:
  - name: maestro-redis
    version: 0.1.0
    repository: http://helm.tfgco.com
  - name: maestro-postgres
    version: 0.1.0
    repository: http://helm.tfgco.com
  - name: maestro-api
    version: 2.3.2
    repository: http://helm.tfgco.com
  - name: maestro-worker
    version: 2.3.2
    repository: http://helm.tfgco.com
  - name: maestro-db-config
    version: 2.3.2
    repository: http://helm.tfgco.com
