version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    target_branch: "next"
    default_labels: 
      - "dependencies"
      - "dependabot"
