name: Format
on: push
jobs:
  goimports:
    name: Perform goimports diff
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.16.3'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Run goimports and diff
      run: |
        make goimports
        @if ! git diff --quiet; then \
          printf 'Found changes. Please run goimports target and commit the changes\n' ; \
          exit 1; \
        fi


